In [1]:
from salsaclrs import SALSACLRSDataset
from salsaclrs import SALSACLRSDataLoader

In [113]:
ds = SALSACLRSDataset(root="./", split="train", algorithm="bfs", num_samples=10, graph_generator="er", graph_generator_kwargs={"n": 4, "p":0.1, "directed": False, 'connected':False}, hints=True)

Processing...
2024-03-04 16:50:25.808 | INFO     | salsaclrs.data:process:326 - Generating bfs dataset with 10 samples on -1 cores
2024-03-04 16:50:25.809 | INFO     | salsaclrs.data:process:327 - Graph generator: er with kwargs {'n': 4, 'p': 0.1, 'directed': False, 'connected': False}


  0%|          | 0/10 [00:00<?, ?it/s]

Done!


In [114]:
dl = SALSACLRSDataLoader(ds, batch_size=32, num_workers=12)

In [115]:
dl.dataset[0]

CLRSData(edge_index=[2, 6], pos=[4], length=1, s=[4], pi=[6], reach_h=[4, 1], pi_h=[6, 1], hints=[2], inputs=[2], outputs=[1])

In [10]:
dl.hints
# get dtype of hints


NameError: name 'dl' is not defined

In [13]:
path = "./bfs/train/graphgenerator=er_n=4_p=0.1_directed=False_connected=False/processed/data_0.pt"
# load tensor from file
import torch
tensor = torch.load(path)
print(tensor)

CLRSData(edge_index=[2, 6], pos=[4], length=1, s=[4], pi=[6], reach_h=[4, 1], pi_h=[6, 1], hints=[2], inputs=[2], outputs=[1])


In [15]:
tensor.inputs

['pos', 's']

In [11]:
type(tensor.hints)

list

In [3]:
tensor.pos

tensor([0.0000, 0.2500, 0.5000, 0.7500])

In [120]:
tensor.edge_index


tensor([[0, 0, 1, 2, 2, 3],
        [0, 2, 1, 0, 2, 3]])

In [99]:
tensor.pi_h.T

tensor([[1., 0., 0., 0., 0., 1., 0., 0., 1., 0., 0., 1.],
        [0., 1., 0., 0., 0., 1., 0., 0., 1., 0., 1., 0.],
        [0., 1., 0., 0., 0., 1., 0., 1., 0., 0., 1., 0.]])

In [87]:
# CLRSData(edge_index=[2, 170], pos=[32], length=5, s=[32], pi=[170], reach_h=[32, 5], pi_h=[170, 5], hints=[2], inputs=[2], outputs=[1])

# show every attribute of the tensor
print(tensor.pi)

tensor([0., 1., 0., 0., 0., 1., 0., 1., 0., 0., 1., 0.], dtype=torch.float64)


In [70]:
def pi_to_node(tensor):
    pi = tensor.pi
    edge_index = tensor.edge_index

    # create a dictionary to map pi to node
    nodes = []
    for i in range(len(pi)):
        if pi[i] > 0:
            nodes.append(edge_index[1][i].item())
    return nodes

print(pi_to_node(tensor))

[10, 10, 12, 12, 8, 2, 3, 14, 13, 20, 12, 12, 12, 12, 12, 12, 12, 13, 12, 12, 11, 11, 12, 10, 11, 18, 12, 19, 14, 2, 12, 12]


In [65]:
len(pi_to_node(tensor))

32

In [88]:
print(tensor.edge_index)

tensor([[0, 0, 0, 0, 1, 1, 1, 2, 2, 3, 3, 3],
        [0, 1, 2, 3, 0, 1, 3, 0, 2, 0, 1, 3]])


In [89]:
# how many nodes are in the graph
print(tensor.s.size(0))

4
